language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION='>=1.7,<1.8'
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.9,<1.10'
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION='>=1.7,<1.8'
install:
  - pip install -r dev-requirements.txt
  - pip uninstall django --yes
  - pip install -q django$DJANGO_VERSION
  - pip install coveralls
  - pip install -e .
before_script:
  - flake8 sparkpost test
script:
  - py.test --cov sparkpost test/ --cov-report term-missing
after_success:
  - coveralls
notifications:
  slack:
    secure: VNIwgvrbcwj0b2gfYSOeTyK7rkV62/belwhYthasHmN+DoTsEJF4+HFVtzOykS72LM/f5Id5zieWtxYG+soy+yEOc1iZizXRpRJORtTYfZJB9RCffavosl322BcpoTX99cGyiZjWjOFH70UWlFMB3zT0jS+9icuTfk7ZqBX/zDA=
